### ISSUE TITLE
chrome에서 flash가 실행되지 않는 현상 해결

### ISSUE THREAD

**Issue by onlyeye26** [vulcan9/jikji.Binder.doc#57]
**현상**
chrome이 69.0.3497.100 버전으로 업데이트 되면서 flash가 실행되지 않음.

**해결방법**
1. flash player를 설치합니다. (31.0.0.108 버전 다운로드 : https://get.adobe.com/kr/flashplayer/)
2. chrome의 웹 주소 왼쪽에 표시되는 자물쇠 ![image](https://user-images.githubusercontent.com/20455074/45857539-234f2900-bd94-11e8-8d40-a34bf40ffa60.png) 또는 정보 ![image](https://user-images.githubusercontent.com/20455074/45857552-3530cc00-bd94-11e8-90fa-0b4410287138.png)를 클릭합니다.
3. 하단에서 사이트 설정을 클릭합니다.
4. 새 탭에서 'Flash' 오른쪽에 있는 허용을 클릭합니다.
5. 사이트로 돌아가서 페이지를 새로고침을 합니다.

* 참고 : https://support.google.com/chrome/answer/6258784

**Comment by vulcan9** [comment]
![c1](https://user-images.githubusercontent.com/5111882/50883900-bdfb7280-142c-11e9-85fe-5c0315175759.png)
![c2](https://user-images.githubusercontent.com/5111882/50883901-bdfb7280-142c-11e9-99b6-c0f65e2104ff.png)

**Comment by vulcan9** [comment]
[stop supporting Flash at the end of 2020](https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/)

**Comment by vulcan9** [comment]
### 플래시 지원 중단
`Jik-ji_Binder_0.8.5` 버전부터 `nwJS 0.50.2` 버전을 사용합니다.
따라서 플래시 swf 파일은 바인더에서 더이상 사용할 수 없습니다.
