### ISSUE TITLE
nwjs 0.34.1 이미지 로드 메모리 누수

### ISSUE THREAD

**Issue by kenny14** [vulcan9/jikji.Binder.doc#64]
천재 전자저작물 메모리가 증가로 느려지는 현상에 대해 메모리 확인 해봤습니다.
천재 메인화면에서는 2mb 정도 되는 스프라이트 이미지가 21개가 로드되고 있고요.
nwjs 이전버전의 버그로 의심됩니다.

<img width="2560" alt="스크린샷 2020-11-30 오후 3 24 35" src="https://user-images.githubusercontent.com/7077980/100688356-83ef3d00-33c5-11eb-86eb-6ae4c33e0c7f.png">

- 웹 : 그래프를 보면 메인화면에서 뷰어로 갈때 메인화면의 리소스(메모리)가 시스템에 회수되면서 낮아지는걸 볼수 있는데
쭉 보면 쌓이지 않고 메모리가 할당 증가되었다가 회수가 제대로 일어나는걸 볼수 있습니다.

![캡처2(1)](https://user-images.githubusercontent.com/7077980/100688396-97020d00-33c5-11eb-9de8-c015cc253f9c.PNG)

- 직지 바인더 nw 버전 0.32.4 : 바인더에서 돌린경우 메인화면에서 뷰어로 갈때 메인 documents, nodes(녹색, 빨간색)가 회수되지 않고 계속 증가되는걸 볼수 있습니다.

![캡처4](https://user-images.githubusercontent.com/7077980/100688407-a2edcf00-33c5-11eb-94f0-45c9e954f2e2.PNG)

- 직지 바인더 nw 버전 0.50.1 (최신버전) : nw버전을 최신버전으로 테스트 했을때 증상이 사라집니다.

**Comment by vulcan9** [comment]
Binder 0.8.5에서 nwJS 0.50.2 버전 업데이트 되었습니다.

**Comment by kenny14** [comment]
확인 했습니다.
